### ISSUE TITLE
Fix for DS218-j

### ISSUE THREAD

**Issue by theinmostdens** [michealespinola/syno.plexupdate#14] opened 2021-05-14 13:40 UTC
Hi, I have a DS218-j and the script wasn't working. After going through the logs and such, I found that the ArchFamily which is set using uname -m is not identical to what's used in the Plex json - https://plex.tv/api/downloads/5.json. Plex says armv7hf_neon and uname -m says armv7l. I changed from ArchFamily=$(uname -m) to ArchFamily="armv7hf_neon" and everything works. Maybe an option in the config file to manually set (and override) ArchFamily for those Synology NAS:es (like the DS218-j) that cause problems? I'm not sure how common this is for Synogoys NAS:es, but I had to do the above for the DS218-j. Other than that, the script works really good.

**Comment by michealespinola** [comment] 2021-05-14 22:43
This is a duplicate of open issue #7 

This is being worked on and a config override ability will be released soon.

**Closed as completed by michealespinola** 2021-05-14 22:43 UTC
Labels: duplicate

**Comment by theinmostdens** [comment] 2021-05-15 01:27
Woops, sorry. Didn't see that. Nice!
