### ISSUE TITLE
* UNABLE TO CHECK FOR LATEST VERSION OF PLEX MEDIA SERVER...

### ISSUE THREAD

**Issue by kspreevie** [michealespinola/syno.plexupdate#40] opened 2023-02-27 20:04 UTC
Hi,
Thank you for this script - for me it sometimes doesn't work, and I can't figure out why.
mostly it looks like this:

_SYNO.PLEX UPDATE SCRIPT v4.1.0 for DSM 7

       Script: syno.plexupdate.sh
   Script Dir: /volume1/Scripts/SynoPlexUpdate
  Running Ver: 4.1.0
   Online Ver: 4.1.0
     Released: 2022-07-18 19:34:39+02:00 (224+ days old)
               * No new version found.

 * UNABLE TO CHECK FOR LATEST VERSION OF PLEX MEDIA SERVER...

date: invalid date '@'
     Synology: DS920+ (x86_64), DSM 7.1.1-42962 Update 4
     Plex Dir: /volume1/PlexMediaServer/AppData/Plex Media Server
   Plex Token: xxx
  Running Ver: 1.31.1.6733
               * No new version found._
               
            
sometimes it works:

_SYNO.PLEX UPDATE SCRIPT v4.1.0 for DSM 7

       Script: syno.plexupdate.sh
   Script Dir: /volume1/Scripts/SynoPlexUpdate
  Running Ver: 4.1.0
   Online Ver: 4.1.0
     Released: 2022-07-18 19:34:39+02:00 (222+ days old)
               * No new version found.

     Synology: DS920+ (x86_64), DSM 7.1.1-42962 Update 4
     Plex Dir: /volume1/PlexMediaServer/AppData/Plex Media Server
   Plex Token: xxx
  Running Ver: 1.31.1.6733
   Online Ver: 1.31.1.6733 (Beta Channel)
     Released: 2023-02-20 15:29:08+01:00 (6+ days old)
               * No new version found._
               

what I tried: check connection, check DNS Servers, check Date/Time on the NAS, check if the connection to the NTP Server is working.

what can be the problem?
Thanks in advance.

**Comment by kspreevie** [comment] 2023-02-27 20:08
sorry I saw there was the same issue already

**Comment by michealespinola** [comment] 2023-02-28 08:02
Closing as duplicate of issue #35

**Closed as completed by michealespinola** 2023-02-28 08:02 UTC
Labels: duplicate, DSM7
